### ISSUE TITLE
no train folder generated after running prepare_polyp() in prepare_dataset.py

### ISSUE THREAD

**Issue by f414158949** [jcwang123/FedLC#3]
After running prepare_polyp() in prepare_dataset.py, 4 Site folders generated (Site1, Site2, Site3, Site4) but there are no "train" folders in Site1 and Site4.

**Comment by jcwang123** [comment]
Any prints in the console?

**Comment by jcwang123** [comment]
Please print the variable "image_path". It may be due that the function (glob) has not found any samples.
